services:
  api:
    build: .
    container_name: cafe_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
      - WATCHFILES_FORCE_POLLING=1
    command: >
      /app/.venv/bin/uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app/src
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:15
    container_name: cafe_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_cafe_data:/var/lib/postgresql/data

volumes:
  postgres_cafe_data:
